In [36]:
#numpy type
import numpy as np
N=np.array([10,20,30,40])
print(type(N))

<class 'numpy.ndarray'>


In [37]:
#sum in numpy
import numpy as np

arr = np.array([1, 2, 3, 4])

total = np.sum(arr)
print(total)


10


In [38]:
#row sum
arr = np.array([[1, 2],
                [3, 4]])
row_sum = np.sum(arr, axis=1)
print(row_sum)


[3 7]


In [39]:
#col sum
col_sum = np.sum(arr, axis=0)
print(col_sum)


[4 6]


In [40]:
#dim
import numpy as np

a = np.array(5)
print(a.ndim)


0


In [41]:
a = np.array([1, 2, 3, 4])
print(a.ndim)


1


In [42]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(a.ndim)


2


In [43]:
#shapeing
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.shape)


(2, 3)


In [44]:
#delacring zero's
import numpy as np

a = np.zeros(5)
print(a)


[0. 0. 0. 0. 0.]


In [45]:
#delacring one's

a = np.ones((2, 3))
print(a)


[[1. 1. 1.]
 [1. 1. 1.]]


In [46]:
#arrays iD
import numpy as np

a = np.array([10, 20, 30, 40, 50])

print(a[0])   
print(a[2])   
print(a[-1])  


10
30
50


In [47]:
#arrays 2D

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a[0, 0])  
print(a[0, 2])  
print(a[1, 1])  


1
3
5


In [48]:
n=np.array([1,2,3,4,5])
print(n[-1])

5


In [49]:
import numpy as np

n = np.array([[1, 2, 3], [4, 5, 6]])
print(n[0, -1])


3


In [50]:
import numpy as np

a = np.array([1, 2, 3, 4,5])
print(a.shape)


(5,)


In [51]:
a = np.array([[1, 2, 3,4,5,6],
              [6,7,8,9,3,2]])

print(a.shape)


(2, 6)


In [52]:
#reshaping
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])

print(a.shape)
print(a.reshape(2, 3))



(6,)
[[1 2 3]
 [4 5 6]]


In [53]:
#looping for 1D
a = np.array([10, 20, 30, 40])

for x in a:
    print(x)


10
20
30
40


In [54]:
#looping for 2D
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

for row in a:
    print(row)


[1 2 3]
[4 5 6]


In [55]:
#joinng array
n1 = np.array([1, 2, 3])
n2= np.array([4, 5, 6])

c = np.concatenate((n1, n2))
print(c)

[1 2 3 4 5 6]
